import vm from 'node:vm';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const nodes = new Map();
const context2d = new Proxy({}, {get: (_,key)=>()=>{}});
function node(id) {
 if (!nodes.has(id)) nodes.set(id, {value:'', checked:false, disabled:false, classList:{toggle(){}}, addEventListener(event,fn){this[event]=fn;}, getContext(){return context2d;}, width:420,height:560});
 return nodes.get(id);
}
node('#visible-watermark').checked=true;
node('#invisible-same-text').checked=true;
node('#watermark-text').value='CONFIDENTIAL';
node('#watermark-color').value='#333333';
const ctx=vm.createContext({document:{querySelector:node,documentElement:{dataset:{}}},__APP_VERSION__:'test',generatePermissionPassword:()=> 'test-password'});
const code=readFileSync(new URL('../src/main.js', import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replaceAll('import.meta.url', '"https://test.invalid/src/main.js"');
vm.runInContext(code,ctx);
const options=()=>vm.runInContext('getOptions()',ctx);
assert.equal(options().invisibleText,'');
node('#invisible-watermark').checked=true;
node('#invisible-watermark').input();
assert.equal(options().invisibleText,'CONFIDENTIAL');
node('#watermark-text').value='Recipient 测试';
node('#watermark-text').input();
assert.equal(options().invisibleText,'Recipient 测试');
assert.equal(node('#invisible-text').value,'Recipient 测试');
node('#invisible-same-text').checked=false;
node('#invisible-same-text').input();
assert.equal(node('#invisible-text').disabled,false);
node('#invisible-text').value='Separate ID';
node('#watermark-text').value='New visible';
node('#watermark-text').input();
assert.equal(options().invisibleText,'Separate ID');
node('#invisible-same-text').checked=true;
node('#invisible-same-text').input();
assert.equal(options().invisibleText,'New visible');
node('#visible-watermark').checked=false;
node('#visible-watermark').input();
assert.equal(options().visible,false);
assert.equal(options().invisibleText,'New visible');
assert.equal(node('#visible-controls').disabled,true);
console.log('PASS UI defaults, live text sync, custom override, and invisible-only mode');
